<?php
$this->title = 'View message';
$this->toolbarIcon = 'icon-48-inbox';

$this->addButtons = array();
if (   $this->object->mcs_processor === 'Internal' 
    && $this->object->mcr_to === MessageCenter_Message::getInternalReplyMail()) 
{
    $this->addButtons['reply'] = array('td_id' => 'reply', 'icon_name' => 'edit', 'title' => 'Reply', 'url' => $this->url(array_merge($this->inflection, array('action' => 'reply', 'mcm_id' => $this->object->mcm_id)), 'section-default', true));    
}
$this->addButtons['cancel'] = array('td_id' => 'toolbar-cancel', 'icon_name' => 'cancel', 'title' => 'Close', 'url' => $this->url(array_merge($this->inflection, array('action' => 'getlist')), 'section-default', true));    
?>
<div class="padding">
    <?php echo $this->partial('toolbar/empty.phtml', $this->getVars()); ?>
    <div id="element-box">
		<div class="t"><div class="t"><div class="t"></div></div></div>
    		<div class="m">
    			<fieldset>
    				<legend>View message</legend>
        			<table class="admintable">
            			<tr>
            				<td class="key">From:</td>
            				<td><?php echo $this->object->mcs_from?></td>
            			</tr>
            			<tr>
            				<td class="key">To:</td>
            				<td><?php echo $this->object->mcr_to?></td>
            			</tr>
            			<tr>
            				<td class="key">Added:</td>
            				<td><?php echo $this->object->mcm_added != '0000-00-00 00:00:00' ? date('m/d/Y H:i:s', strtotime($this->object->mcm_added)) : ''?></td>
            			</tr>
            			<tr>
            				<td class="key">Processor:</td>
            				<td><?php echo $this->object->mcs_processor?></td>
            			</tr>            			
            			<tr>
            				<td class="key">Subject:</td>
            				<td><?php echo nl2br($this->escape($this->object->mcm_subject))?></td>
            			</tr>
            			<tr>
            				<td class="key">Body:</td>
            				<td><?php echo $this->object->mcm_body?></td>
            			</tr>
        			</table>	    				
    			</fieldset>
    		</div>		
		<div class="b"><div class="b"><div class="b"></div></div></div>
	</div>
</div>